services:
  postgres:
    image: postgres:14
    container_name: business_outreach_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: business_outreach
    volumes:
      - postgres_data:/var/lib/postgresql/data

  langgraph-service:
    build: ./research
    container_name: langgraph-service
    ports:
      - "8000:8000"
    env_file:
      - ./research/.env
    environment:
      - PYTHONPATH=/app

volumes:
  postgres_data:
